/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ArbolControlador;
import Modelo.ArbolBinario;
import java.awt.Toolkit;

/**
 *
 * @author Sofito-Chan
 */
public class UIArbol01 extends javax.swing.JFrame {

    /**
     * Creates new form ingresarArbol
     */
    public UIArbol01() {
        arbol = new ArbolBinario();
        lienzo = new Lienzo();
        control = new ArbolControlador(arbol, lienzo);
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("codeIcon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        enunciado = new javax.swing.JLabel();
        buttonCantiNodos = new javax.swing.JButton();
        buttonString = new javax.swing.JButton();
        buttonInPre = new javax.swing.JButton();
        buttonCInPos = new javax.swing.JButton();
        labelFirma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Segunda Práctica - Lógica 3");
        setResizable(false);

        panel.setBackground(new java.awt.Color(204, 255, 204));

        enunciado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enunciado.setForeground(new java.awt.Color(0, 0, 0));
        enunciado.setText("Elige la forma de ingresar el árbol binario:");

        buttonCantiNodos.setBackground(new java.awt.Color(102, 255, 102));
        buttonCantiNodos.setForeground(new java.awt.Color(0, 0, 0));
        buttonCantiNodos.setText("Cantidad de Nodos (Tamaño)");
        buttonCantiNodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCantiNodosActionPerformed(evt);
            }
        });

        buttonString.setBackground(new java.awt.Color(102, 255, 102));
        buttonString.setForeground(new java.awt.Color(0, 0, 0));
        buttonString.setText("Nodos separados por comas");
        buttonString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStringActionPerformed(evt);
            }
        });

        buttonInPre.setBackground(new java.awt.Color(102, 255, 102));
        buttonInPre.setForeground(new java.awt.Color(0, 0, 0));
        buttonInPre.setText("Recorridos Inorden y Preorden");
        buttonInPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInPreActionPerformed(evt);
            }
        });

        buttonCInPos.setBackground(new java.awt.Color(102, 255, 102));
        buttonCInPos.setForeground(new java.awt.Color(0, 0, 0));
        buttonCInPos.setText("Recorridos Inorden y Posorden");
        buttonCInPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCInPosActionPerformed(evt);
            }
        });

        labelFirma.setForeground(new java.awt.Color(0, 51, 0));
        labelFirma.setText("John Rodriguez y Sofia Vanegas - Segunda Práctica - Lógica 3");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonInPre, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(buttonString, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCantiNodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCInPos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78))
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(enunciado))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelFirma)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(enunciado)
                .addGap(27, 27, 27)
                .addComponent(buttonCantiNodos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonString, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonInPre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCInPos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelFirma)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCantiNodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCantiNodosActionPerformed
//        ArbolNegocio negocio = new ArbolNegocio();
//        
//        try{
//            n = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Elige un número de nodos (Mín: 1, Max: 20)", "Cantidad de nodos", 3));
//            if (!negocio.verificarCantidadNodos(n)){
//                JOptionPane.showMessageDialog(rootPane, "El número no es válido.");
//                return;
//            }
//        }
//        catch(NumberFormatException e){
//            JOptionPane.showMessageDialog(rootPane, "Por favor coloque valores númericos válidos", "Error", 2);
//            return;
//        }        
//        int f = JOptionPane.showConfirmDialog(rootPane, "¿Quiere identificar los nodos con letras?");
//        switch(f){
//            //si
//            case 0:
//                arbol.ConstruyeArbolBinario1(n, true);
//                break;
//            //no
//            case 1:
//                arbol.ConstruyeArbolBinario1(n, false);
//                break;
//            case 2:
//                return;
//        }

        arbol.ConstruyeArbolBinario1(size, true);
        lienzo();
    }//GEN-LAST:event_buttonCantiNodosActionPerformed

    private void buttonStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStringActionPerformed
        //String arbolB = JOptionPane.showInputDialog(rootPane, "Ingrese los nombres de los nodos separados por comas (Max: 25 nodos)", "Nodos separados por comas", 3);
        arbol.ConstruyeArbolBinario2(arbolB);
        lienzo();

    }//GEN-LAST:event_buttonStringActionPerformed

    private void buttonCInPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCInPosActionPerformed
        arbol.construyeInPos(in, pos);
        lienzo();
    }//GEN-LAST:event_buttonCInPosActionPerformed

    private void buttonInPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInPreActionPerformed
        arbol.construyeInPre(in, pre);
        lienzo();
    }//GEN-LAST:event_buttonInPreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIArbol01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIArbol01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIArbol01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIArbol01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIArbol01().setVisible(true);
            }
        });
    }
    
    
    public void setControl(ArbolControlador control) {
        this.control = control;
    }
        
    public void lienzo() {        
        UIArbol02 lienzo = new UIArbol02();
        lienzo.setControl(control);
        lienzo.dibujarArbol();
        lienzo.setVisible(true);
        this.setVisible(false);
    }
    
    String in = "G,H,O,Q,R,T,X";
    String pos = "H,O,R,Q,X,T,G";
    String pre = "G,T,Q,O,H,R,X";
    String arbolB = "k,j,b,i,h,g,a,c,e,d,f";
    int size = 20;
    private ArbolBinario arbol; //MODELO
    private Lienzo lienzo; //PANEL-ARBOL
    private ArbolControlador control; //CONTROLADOR
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCInPos;
    private javax.swing.JButton buttonCantiNodos;
    private javax.swing.JButton buttonInPre;
    private javax.swing.JButton buttonString;
    private javax.swing.JLabel enunciado;
    private javax.swing.JLabel labelFirma;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
