/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ArbolControlador;
import java.awt.BorderLayout;
import java.awt.Rectangle;
import java.awt.Toolkit;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;

/**
 *
 * @author Sofito-Chan
 */
public class UIArbol02 extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public UIArbol02() {
        initComponents();
        //buttonRecargar.setVisible(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("codeIcon.png")));
    }    

    public void dibujarArbol() {         
        control.iniciar();
        panelArbol.removeAll();
        internalFrame();        
    }
    private void internalFrame(){
        Rectangle tamaño = InternalFrameArbol.getBounds();
        this.InternalFrameArbol = null;
        this.InternalFrameArbol = new JInternalFrame();
        this.panelArbol.add(InternalFrameArbol, JLayeredPane.DEFAULT_LAYER);
        this.InternalFrameArbol.setVisible(true);
        this.InternalFrameArbol.setBounds(tamaño);
        //this.InternalFrameArbol.set;
        this.InternalFrameArbol.setEnabled(false);
        this.InternalFrameArbol.add(control.getLienzo(), BorderLayout.CENTER);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelArbol = new javax.swing.JPanel();
        InternalFrameArbol = new javax.swing.JInternalFrame();
        panel = new javax.swing.JPanel();
        buttonDetalles = new javax.swing.JButton();
        buttonNuevoArbol = new javax.swing.JButton();
        buttonDetalles1 = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Segunda Práctica - Lógica 3");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(204, 255, 204));
        setResizable(false);

        panelArbol.setBackground(new java.awt.Color(204, 255, 204));
        panelArbol.setForeground(new java.awt.Color(255, 255, 255));
        panelArbol.setEnabled(false);
        panelArbol.setPreferredSize(new java.awt.Dimension(800, 400));

        InternalFrameArbol.setBackground(new java.awt.Color(255, 255, 255));
        InternalFrameArbol.setBorder(null);
        InternalFrameArbol.setClosable(true);
        InternalFrameArbol.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        InternalFrameArbol.setForeground(new java.awt.Color(255, 255, 255));
        InternalFrameArbol.setIconifiable(true);
        InternalFrameArbol.setMaximizable(true);
        InternalFrameArbol.setToolTipText("");
        InternalFrameArbol.setAutoscrolls(true);
        InternalFrameArbol.setPreferredSize(new java.awt.Dimension(800, 400));
        InternalFrameArbol.setVisible(true);

        javax.swing.GroupLayout InternalFrameArbolLayout = new javax.swing.GroupLayout(InternalFrameArbol.getContentPane());
        InternalFrameArbol.getContentPane().setLayout(InternalFrameArbolLayout);
        InternalFrameArbolLayout.setHorizontalGroup(
            InternalFrameArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        InternalFrameArbolLayout.setVerticalGroup(
            InternalFrameArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelArbolLayout = new javax.swing.GroupLayout(panelArbol);
        panelArbol.setLayout(panelArbolLayout);
        panelArbolLayout.setHorizontalGroup(
            panelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArbolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InternalFrameArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelArbolLayout.setVerticalGroup(
            panelArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArbolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InternalFrameArbol, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel.setBackground(new java.awt.Color(204, 255, 204));
        panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel.setForeground(new java.awt.Color(255, 255, 255));
        panel.setEnabled(false);

        buttonDetalles.setBackground(new java.awt.Color(102, 255, 102));
        buttonDetalles.setForeground(new java.awt.Color(0, 0, 0));
        buttonDetalles.setText("Detalles del arbol");
        buttonDetalles.setToolTipText("Altura,grado,hijas, recorridos (in, pre y pos)");
        buttonDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDetallesActionPerformed(evt);
            }
        });

        buttonNuevoArbol.setBackground(new java.awt.Color(102, 255, 102));
        buttonNuevoArbol.setForeground(new java.awt.Color(0, 0, 0));
        buttonNuevoArbol.setText("Nuevo Arbol");
        buttonNuevoArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNuevoArbolActionPerformed(evt);
            }
        });

        buttonDetalles1.setBackground(new java.awt.Color(102, 255, 102));
        buttonDetalles1.setForeground(new java.awt.Color(0, 0, 0));
        buttonDetalles1.setText("Detalles de un nodo");
        buttonDetalles1.setToolTipText("Hijos, hermanos, padre, ancestros, tio , abuelo");
        buttonDetalles1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDetalles1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setFocusable(false);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDetalles1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(buttonNuevoArbol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextArea1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonNuevoArbol)
                .addGap(18, 18, 18)
                .addComponent(buttonDetalles)
                .addGap(18, 18, 18)
                .addComponent(buttonDetalles1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelArbol, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelArbol, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelArbol.getAccessibleContext().setAccessibleName("Arboles Binarios");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDetallesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDetallesActionPerformed

    private void buttonNuevoArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNuevoArbolActionPerformed
        UIArbol01 menu = new UIArbol01();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonNuevoArbolActionPerformed

    private void buttonDetalles1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDetalles1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDetalles1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIArbol02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIArbol02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIArbol02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIArbol02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIArbol02().setVisible(true);
            }
        });
    } 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame InternalFrameArbol;
    private javax.swing.JButton buttonDetalles;
    private javax.swing.JButton buttonDetalles1;
    private javax.swing.JButton buttonNuevoArbol;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelArbol;
    // End of variables declaration//GEN-END:variables

    private ArbolControlador control; //CONTROL

    public void setControl(ArbolControlador control) {
        this.control = control;
    } 
}
